editSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:
    multiInput:
    multiRow:
    treeView:

indexSuccess:
  javascripts:
    blank:
    treeView:

listSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

relatedAuthoritiesSuccess:
  javascripts:
    blank:
