browseSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:
    blank:

indexSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:
    blank:

listSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:
