browseSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

editPhysicalObjectsSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:
    multiDelete:

listSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

physicalObjects:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

addDigitalObjectSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/container/container-min:
    blank:

multiFileUploadSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/container/container-min:
    description:
    blank:

storageLocationsSuccess:
  stylesheets:
    print-reports: { media: screen, position: last }

fileListSuccess:
  stylesheets:
    print-reports: { media: screen, position: last }

itemListSuccess:
  stylesheets:
    print-reports: { media: screen, position: last }

renameSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/container/container-min:
    /vendor/yui/connection/connection-min:
    repositoryHoldings:
    description:
    rename:
