browseSuccess:
  stylesheets:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/ui/ui.all.css:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/ui/ui.datepicker.js:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:

editPhysicalObjectsSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:
    multiDelete:

listSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

physicalObjects:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

addDigitalObjectSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/container/container-min:
    blank:

multiFileUploadSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/container/container-min:
    description:
    blank:

storageLocationsSuccess:
  stylesheets:
    print-reports: { media: screen, position: last }

renameSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/container/container-min:
    /vendor/yui/connection/connection-min:
    repositoryHoldings:
    description:
    rename:

updatePublicationStatusSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/container/container-min:
    /vendor/yui/connection/connection-min:
    repositoryHoldings:

uploadFindingAidSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/container/container-min:
    repositoryHoldings:

all:
  components:
    css:
      [informationobject, stylesheet]
