importSelectSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/textarea:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:
    blank:
    multiInstanceInput:
    multiRow:
    select:

validateCsvSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/textarea:

addDigitalObjectSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    blank:

editPhysicalObjectsSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:
    multiDelete:
