# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:

  # Upload limit (in gigabytes), possible values:
  #  Zero              => Uploads forbidden
  #  Negative integer  => Unlimited uploads
  #  Positive integer  => Number of gigabytes
  upload_limit: -1

  # Timeout for fetching digital objects from external services, in seconds
  download_timeout: 10

  # Use sfMemcacheCache if you want a distributed cache.
  # sfAPCCache can do the trick for a single instance (sfAPCuCache in PHP 5.5).
  cache_engine: sfAPCCache

  # Enable read only mode
  read_only: false

  # gearmand address
  gearman_job_server: 127.0.0.1:4730

  # Used in the repo template
  # google_maps_api_key: ...

  # Google Analitycs
  # google_analytics_api_key: ...
