globalReplaceSuccess:
  stylesheets:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    multiRow:

descriptionUpdatesSuccess:
  stylesheets:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/ui/ui.all.css:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/ui/ui.datepicker.js:
    clipboardToggleAll:
    descUpdToggleIoOptions:
