editSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /plugins/sfDrupalPlugin/vendor/drupal/modules/user/user:
    select:

editActorAclSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:

editRepositoryAclSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:

editInformationObjectAclSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    /vendor/yui/container/container-min:
    autocomplete:
    aclDialog:

editTermAclSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:

indexSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    editingHistory:
    blank:

indexActorAclSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:
    blank:

indexRepositoryAclSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:
    blank:

indexTermAclSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:
    blank:

indexInformationObjectAclSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:
    blank:

listSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

passwordEditSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/modules/user/user:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
